### ISSUE TITLE
Hot code reload during development

### ISSUE THREAD

**Issue by benbro** [angular/closure-demo#14]
Is there a setup for hot code reload similar to the webpack setup or do I need to re-compile each time I make a change?

Are there plans to sync the angular version in this demo with the latest release?

Are there examples for adding third-party npm modules?
Is it possible to add static files like CSS and images?

Is this setup recommended for production or is it just a prof of concept?

**Comment by MarkPieszak** [comment]
I believe this is more of a proof of concept at this moment @benbro

**Comment by alexeagle** [comment]
It's actually not even wise to do hot code reload - closure compiler is a production bundler and too slow to run in development mode. We do have plans to externalize our development server, see https://github.com/bazelbuild/rules_typescript/issues/19

https://github.com/angular/angular/tree/master/integration/hello_world__closure is the always-up-to-date example because it's run in the Angular CI. I could sync this repo again, I'll certainly do that for Angular 5.0.0.

Third-party libraries with Closure Compiler is a tricky problem, not specific to Angular. Usage varies among libraries. I hope we'll find more time to help with this, something like https://github.com/alexeagle/angular-closure-compatibility to give examples for each library, or get the Closure Compiler team to prioritize this more.

Google apps run with closure compiler in production. This repo demonstrates a supported use of Angular, so yes, we recommend it for production.

**Comment by benbro** [comment]
Thank you for your answer.

Do I need to run something like webpack-dev-server for dev and closure-compiler for production or will your development server replace the need for webpack-dev-server?

**Comment by alexeagle** [comment]
This repo doesn't demonstrate anything useful for development mode - you'd still need some devserver like webpack, or possibly check out https://github.com/alexeagle/angular-bazel-example for a Bazel devserver
